// This will include the generated code from the `storage_service.proto` file.
// The `tonic::include_proto!` macro will look for a file named `storage_service.rs` in the `OUT_DIR`.
// This file is generated by `tonic-build` in `build.rs`.
tonic::include_proto!("storage_service");
